#!/usr/bin/env bash

#############################################################################
# System alases - OS X
#############################################################################

# Colors
eval "$(gdircolors ~/dotfiles/dircolors-solarized/dircolors.256dark)"
alias ls='gls --color=always'
alias ll='ls -alh'

# Clean up LaunchServices to remove duplicates in the “Open With” menu
alias lscleanup='/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -kill -r -domain local -domain system -domain user && killall Finder'

# Recursively delete `.DS_Store` files
alias cleanup="find . -type f -name '*.DS_Store' -ls -delete'"

# Empty the Trash on all mounted volumes and the main HDD
# Also, clear Apple’s System Logs to improve shell startup speed
alias emptytrash='sudo rm -rfv /Volumes/*/.Trashes; sudo rm -rfv ~/.Trash; sudo rm -rfv /private/var/log/asl/*.asl'

# Show/hide hidden files in Finder
alias show='defaults write com.apple.finder AppleShowAllFiles -bool true && killall Finder'
alias hide='defaults write com.apple.finder AppleShowAllFiles -bool false && killall Finder'

# Hide/show all desktop icons (useful when presenting)
alias hidedesktop='defaults write com.apple.finder CreateDesktop -bool false && killall Finder'
alias showdesktop='defaults write com.apple.finder CreateDesktop -bool true && killall Finder'

# URL-encode strings
alias urlencode='python -c "import sys, urllib as ul; print ul.quote_plus(sys.argv[1]);"'

# Disable Spotlight
alias spotoff='sudo mdutil -a -i off'
# Enable Spotlight
alias spoton='sudo mdutil -a -i on'

# Ring the terminal bell, and put a badge on Terminal.app’s Dock icon
# (useful when executing time-consuming commands)
alias badge='tput bel'

# Common programs
alias finder='open .'
alias firefox='open -a Firefox'
alias preview='open -a Preview'
alias unarchiver='open -a "The Unarchiver"'
alias vlc='/Applications/VLC.app/Contents/MacOS/VLC'
alias burp='java -XX:MaxPermSize=1G -Xmx1024m -jar ~/tools/burp/burpsuite_pro.jar > /dev/null 2>&1 &'
alias baudline='/Applications/baudline.app/Contents/MacOS/baudline &'

# Suspend the current account - Effectively going to sleep and putting up the login window
alias afk='/System/Library/CoreServices/Menu\ Extras/User.menu/Contents/Resources/CGSession -suspend'

# Flush Directory Services cache
alias flush="dscache -flushcache && killall -HUP mDNSResponder"
