#!/usr/bin/env bash

#############################################################################
# System alases - Linux
#############################################################################

eval "$(dircolors ~/.dotfiles/dircolors-solarized/dircolors.256dark)"
alias ls="ls --color=always"
alias ll="ls -al"
