#!/usr/bin/env bash

#############################################################################
# System alases - Ubuntu / OS X
#############################################################################

# load osx aliases
if [ $(uname) == "Darwin" ]; then
  source $HOME/dotfiles/bash/aliases-osx
fi

# load linux aliases
if [ $(uname) == "Linux" ]; then
  source $HOME/dotfiles/bash/aliases-linux
fi

# Draw an ascii tree of the filesystem from where you are
alias mytree="find . -type d | sed -e 1d -e 's/[^-][^\/]*\//--/g' -e 's/^/ /' -e 's/-/|-/'"

# Process Management
alias tu='top -o cpu'
alias tm='top -o vsize'

# Less with colors
alias less='less -irX'

# ROT13-encode text. Works for decoding, too! ;)
alias rot13='tr a-zA-Z n-za-mN-ZA-M'

# Enable aliases to be sudo’ed
alias sudo='sudo '

# Gzip-enabled `curl`
alias gurl='curl --compressed'

# quick reload
alias reload="exec $BASH -l"

# common misspellings
alias cd..="cd .."
alias cd.="cd ."

#############################################################################
# Network tools
#############################################################################

# External IP
alias ipext='curl -s http://checkip.dyndns.org/ | grep -o '[0-9][0-9]*.[0-9][0-9]*.[0-9][0-9]*.[0-9]*''

# list all ips 
alias ips="ifconfig -a | grep -o 'inet6\? \(addr:\)\?\s\?\(\(\([0-9]\+\.\)\{3\}[0-9]\+\)\|[a-fA-F0-9:]\+\)' | awk '{ sub(/inet6? (addr:)? ?/, \"\"); print }'"

# Enhanced WHOIS lookups
alias whois="whois -h whois-servers.net"
