#!/usr/bin/env bash

# Auto Completion
bind "$(set completion-ignore-case on)"
bind "$(set show-all-if-ambiguous on)"

if [ -d "$HOME"/dotfiles/bash_completion.d ]; then
  for usrcomp in $("$HOME"/dotfiles/bash/bash_completion.d/*); do
    if [ -f "$usrcomp" ]; then
      usrcomp="$HOME""/dotfiles/bash/bash_completion.d/""$usrcomp"
      echo $usrcomp
      source "$usrcomp";
    fi;
  done
  unset usrcomp
fi
