#!/usr/bin/env bash

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

#set up bash
for file in "$HOME"/dotfiles/bash/{path,exports,functions,bash_prompt,aliases}; do
  [ -r "$file" ] && [ -f "$file" ] && source "$file"
done
unset file

if [ "$(uname)" == "Darwin" ]; then
  source "$HOME"/dotfiles/bash/bash_profile-osx
fi

# Case-insensitive globbing (used in pathname expansion)
shopt -s nocaseglob
# Append to the Bash history file, rather than overwriting it
shopt -s histappend
# Autocorrect typos in path names when using `cd`
shopt -s cdspell
# Check the window size after each command and, if neccessary
# update the value of LINES and COLUMNS
shopt -s checkwinsize

# Enable some Bash 4 features when possible:
# * `autocd`, e.g. `**/qux` will enter `./foo/bar/baz/qux`
# * Recursive globbing, e.g. `echo **/*.txt`
for option in autocd globstar; do
  shopt -s "$option" 2> /dev/null
done
