#!/usr/bin/env bash

export EDITOR="vim"

export HISTSIZE=1000
export HISTFILESIZE=2000

# Don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
export HISTCONTROL=ignoreboth

# Make some commands not show up in history
export HISTIGNORE="ls:cd:cd -:pwd:exit:date:* --help:df:ll:man:w:h:top"

# Prefer US English and use UTF-8
export LANG="en_US"
export LC_ALL="en_US.UTF-8"

if [ "$TERM" == "screen" ]; then
export TERM="xterm-256color"
fi

# Highlight section titles in manual pages
# export LESS_TERMCAP_md="$ORANGE"

# Don’t clear the screen after quitting a manual page
export MANPAGER="less -X"
export PAGER="less"

# Always enable colored `grep` output
export GREP_OPTIONS="--color=auto"

# Link Homebrew casks in `/Applications` rather than `~/Applications`
# export HOMEBREW_CASK_OPTS="--appdir=/Applications"
