#!/usr/bin/env bash

function pman()
{
  man -t "${1}" | open -f -a /Applications/Preview.app
}

# Change working directory to the top-most Finder window location
#cdf - Change Directory to the active Finder window (else ~/Desktop)
function cdf()
{
  local fPath 
  fPath=$(osascript -e '
        tell app "finder"
            try
                  set folderPath to (folder of the front window as alias)
                      on error
                            set folderPath to (path to desktop folder as alias)
                                end try
                                      POSIX path of folderPath
  end tell'
  );
  echo "cd $fPath";
  cd "$fPath" > /dev/null
}

# Use Git’s colored diff when available
hash git &>/dev/null
if [ $? -eq 0 ]; then
  function diff() {
    git diff --no-index --color-words "$@"
  }
fi

# Compare original and gzipped file size
function gz() {
  local origsize
  local gzipsize
  local ratio
  origsize=$(wc -c < "$1")
  gzipsize=$(gzip -c "$1" | wc -c)
  ratio=$(echo "$gzipsize * 100/ $origsize" | bc -l)
  printf "orig: %d bytes\n" "$origsize"
  printf "gzip: %d bytes (%2.2f%%)\n" "$gzipsize" "$ratio"
}

# All the dig info
function digga() {
  dig +nocmd "$1" any +multiline +noall +answer
}

# `tre` is a shorthand for `tree` with hidden files and color enabled, ignoring
# the `.git` directory, listing directories first. The output gets piped into
# `less` with options to preserve color and line numbers, unless the output is
# small enough for one screen.
function tre() {
  tree -aC -I '.git|node_modules|bower_components' --dirsfirst "$@" | less -FRNX
}
